# Generated by Django 3.2.20 on 2024-07-04 12:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.IntegerField(blank=True, choices=[(1, 'Admin'), (2, 'Buyer'), (3, 'Supplier'), (4, 'Vendor')], null=True)),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('address1', models.CharField(blank=True, max_length=100, null=True)),
                ('pin', models.CharField(blank=True, max_length=10, null=True)),
                ('additional_email', models.TextField(blank=True, null=True)),
                ('count', models.IntegerField(blank=True, default=0, null=True)),
                ('blocktime', models.DateTimeField(blank=True, null=True)),
                ('active', models.BooleanField(default=False)),
                ('reset_password', models.CharField(blank=True, max_length=100, null=True)),
                ('buying_email', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
