# Generated by Django 3.2.20 on 2024-07-18 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('pin', models.CharField(blank=True, max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Domimp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Drop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('desc', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fabric_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Factory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factory_name', models.CharField(blank=True, max_length=100, null=True)),
                ('factory_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('factory_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('factory_address', models.CharField(blank=True, max_length=500, null=True)),
                ('factory_city', models.CharField(blank=True, choices=[('Delhi', 'Delhi'), ('Kolkata', 'Kolkata'), ('Mumbai', 'Mumbai'), ('Hyderabad', 'Hyderabad'), ('Bengaluru', 'Bengaluru'), ('Chennai', 'Chennai'), ('Ahmedabad', 'Ahmedabad'), ('Surat', 'Surat'), ('Pune', 'Pune'), ('Jaipur', 'Jaipur'), ('Kanpur', 'Kanpur'), ('Lucknow', 'Lucknow'), ('Nagpur', 'Nagpur'), ('Ghaziabad', 'Ghaziabad'), ('Indore', 'Indore'), ('Coimbatore', 'Coimbatore'), ('Patna', 'Patna'), ('Visakhapatnam', 'Visakhapatnam'), ('Bhopal', 'Bhopal'), ('Nashik', 'Nashik'), ('Pimpri-Chinchwad', 'Pimpri-Chinchwad'), ('Agra', 'Agra'), ('Vadodara', 'Vadodara'), ('Ludhiana', 'Ludhiana'), ('Madurai', 'Madurai'), ('Varanasi', 'Varanasi'), ('Meerut', 'Meerut'), ('Faridabad', 'Faridabad'), ('Jamshedpur', 'Jamshedpur'), ('Rajkot', 'Rajkot'), ('Jabalpur', 'Jabalpur'), ('Asansol', 'Asansol'), ('Allahabad', 'Allahabad'), ('Dhanbad', 'Dhanbad'), ('Srinagar', 'Srinagar'), ('Aurangabad', 'Aurangabad'), ('Jodhpur', 'Jodhpur'), ('Amritsar', 'Amritsar'), ('Ranchi', 'Ranchi'), ('Gwalior', 'Gwalior'), ('Chandigarh', 'Chandigarh'), ('Vijayawada', 'Vijayawada'), ('Tiruchirappalli', 'Tiruchirappalli'), ('Raipur', 'Raipur'), ('Kota', 'Kota'), ('Bareilly', 'Bareilly'), ('Guwahati', 'Guwahati'), ('Tirupur', 'Tirupur'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Solapur', 'Solapur'), ('Hubli', 'Hubli'), ('Salem', 'Salem'), ('Aligarh', 'Aligarh'), ('Gurgaon', 'Gurgaon'), ('Durg', 'Durg'), ('Moradabad', 'Moradabad'), ('Mysore', 'Mysore'), ('Bhubaneswar', 'Bhubaneswar'), ('Jalandhar', 'Jalandhar'), ('Warangal', 'Warangal'), ('Guntur', 'Guntur'), ('Dehradun', 'Dehradun'), ('Bhiwandi', 'Bhiwandi'), ('Saharanpur', 'Saharanpur'), ('Siliguri', 'Siliguri'), ('Gorakhpur', 'Gorakhpur'), ('Cuttack', 'Cuttack'), ('Pondicherry', 'Pondicherry'), ('Amravati', 'Amravati'), ('Bikaner', 'Bikaner'), ('Faizabad', 'Faizabad'), ('Kochi', 'Kochi'), ('Firozabad', 'Firozabad'), ('Bhavnagar', 'Bhavnagar'), ('Durgapur', 'Durgapur'), ('Bokaro Steel City', 'Bokaro Steel City'), ('Naya Raipur', 'Naya Raipur'), ('Rourkela', 'Rourkela'), ('Ajmer', 'Ajmer'), ('Nanded', 'Nanded'), ('Kolhapur', 'Kolhapur'), ('Jhansi', 'Jhansi'), ('Gulbarga', 'Gulbarga'), ('Agartala', 'Agartala'), ('Erode', 'Erode'), ('Ujjain', 'Ujjain'), ('Sangli-Miraj-Kupwad', 'Sangli-Miraj-Kupwad'), ('Jammu', 'Jammu'), ('Nellore', 'Nellore'), ('Mangalore', 'Mangalore'), ('Tirunelveli', 'Tirunelveli'), ('Muzaffarnagar', 'Muzaffarnagar'), ('Belgaum', 'Belgaum'), ('Vellore', 'Vellore'), ('Jamnagar', 'Jamnagar'), ('Udaipur', 'Udaipur'), ('Gaya', 'Gaya'), ('Jalgaon', 'Jalgaon'), ('Mathura', 'Mathura'), ('Patiala', 'Patiala'), ('Panipat', 'Panipat'), ('Davangere', 'Davangere'), ('Calicut', 'Calicut'), ('Akola', 'Akola'), ('Kurnool', 'Kurnool'), ('Rajamahendravaram', 'Rajamahendravaram'), ('Latur', 'Latur'), ('Tuticorin', 'Tuticorin'), ('Bhagalpur', 'Bhagalpur'), ('Malegaon', 'Malegaon'), ('Bellary', 'Bellary'), ('Ambala', 'Ambala'), ('Muzaffarpur', 'Muzaffarpur'), ('Yamunanagar', 'Yamunanagar'), ('Dhule', 'Dhule'), ('Dimapur', 'Dimapur'), ('Tirupati', 'Tirupati'), ('Rohtak', 'Rohtak'), ('Sagar', 'Sagar'), ('Budaun', 'Budaun'), ('Korba', 'Korba'), ('Bhilwara', 'Bhilwara'), ('Rampur', 'Rampur'), ('Shahjahanpur', 'Shahjahanpur'), ('Berhampur', 'Berhampur'), ('Ahmednagar', 'Ahmednagar'), ('Kollam', 'Kollam'), ('Bardhaman', 'Bardhaman'), ('Kadapa', 'Kadapa'), ('Alwar', 'Alwar'), ('Bilaspur', 'Bilaspur'), ('Nandurbar', 'Nandurbar'), ('Bijapur', 'Bijapur'), ('Ichalkaranji', 'Ichalkaranji'), ('Thrissur', 'Thrissur'), ('Chandrapur', 'Chandrapur'), ('Malda', 'Malda'), ('Shimoga', 'Shimoga'), ('Junagadh', 'Junagadh'), ('Farrukhabad', 'Farrukhabad'), ('Kakinada', 'Kakinada'), ('Nizamabad', 'Nizamabad'), ('Purnia', 'Purnia'), ('Haridwar', 'Haridwar'), ('Hisar', 'Hisar'), ('Darbhanga', 'Darbhanga'), ('Tumkur', 'Tumkur'), ('Baharampur', 'Baharampur'), ('Habra', 'Habra'), ('Jalpaiguri', 'Jalpaiguri'), ('Karnal', 'Karnal'), ('Ozhukarai', 'Ozhukarai'), ('Bihar Sharif', 'Bihar Sharif'), ('Kharagpur', 'Kharagpur'), ('Aizawl', 'Aizawl'), ('Sonipat', 'Sonipat'), ('Gudiyatham', 'Gudiyatham'), ('Dewas', 'Dewas'), ('Shantipur', 'Shantipur'), ('Bathinda', 'Bathinda'), ('Jalna', 'Jalna'), ('Satna', 'Satna'), ('Mau', 'Mau'), ('Roorkee', 'Roorkee'), ('Ratlam', 'Ratlam'), ('Parbhani', 'Parbhani'), ('Sambalpur', 'Sambalpur'), ('Anantapur', 'Anantapur'), ('Imphal', 'Imphal'), ('Rajnandgaon', 'Rajnandgaon'), ('Hapur', 'Hapur'), ('Karimnagar', 'Karimnagar'), ('Arrah', 'Arrah'), ('Noida', 'Noida'), ('Etawah', 'Etawah'), ('Haldwani', 'Haldwani'), ('Bharatpur', 'Bharatpur'), ('Begusarai', 'Begusarai'), ('Sri Ganganagar', 'Sri Ganganagar'), ('Dankuni', 'Dankuni'), ('Gandhidham', 'Gandhidham'), ('Mirzapur', 'Mirzapur'), ('Sikar', 'Sikar'), ('Katihar', 'Katihar'), ('Dhulian', 'Dhulian'), ('Ranaghat', 'Ranaghat'), ('Rewa', 'Rewa'), ('Bulandshahr', 'Bulandshahr'), ('Kannur', 'Kannur'), ('Raichur', 'Raichur'), ('Pali', 'Pali'), ('Ramagundam', 'Ramagundam'), ('Silchar', 'Silchar'), ('Vizianagaram', 'Vizianagaram'), ('Nagercoil', 'Nagercoil'), ('Thanjavur', 'Thanjavur'), ('Katni', 'Katni'), ('Sambhal', 'Sambhal'), ('Singrauli', 'Singrauli'), ('Nadiad', 'Nadiad'), ('Eluru', 'Eluru'), ('Bidar', 'Bidar'), ('Munger', 'Munger'), ('Chhapra', 'Chhapra'), ('Burhanpur', 'Burhanpur'), ('Panchkula', 'Panchkula'), ('Dindigul', 'Dindigul'), ('Gandhinagar', 'Gandhinagar'), ('Hospet', 'Hospet'), ('Bhusawal', 'Bhusawal'), ('Deoghar', 'Deoghar'), ('Ongole', 'Ongole'), ('Puri', 'Puri'), ('Haldia', 'Haldia'), ('Nandyal', 'Nandyal'), ('Khandwa', 'Khandwa'), ('Morena', 'Morena'), ('Raiganj', 'Raiganj'), ('Anand', 'Anand'), ('Bhiwani', 'Bhiwani'), ('Bhind', 'Bhind'), ('Amroha', 'Amroha'), ('Hardoi', 'Hardoi'), ('Vaniyambadi', 'Vaniyambadi'), ('Morbi', 'Morbi'), ('Fatehpur', 'Fatehpur'), ('Kasaragod', 'Kasaragod'), ('Raebareli', 'Raebareli'), ('Daman', 'Daman'), ('Orai', 'Orai'), ('Chhindwara', 'Chhindwara'), ('Barmer', 'Barmer'), ('Sitapur', 'Sitapur'), ('Bahraich', 'Bahraich'), ('Phusro', 'Phusro'), ('Khammam', 'Khammam'), ('Khambhat', 'Khambhat'), ('Sirsa', 'Sirsa'), ('Modinagar', 'Modinagar'), ('Krishnanagar', 'Krishnanagar'), ('Guna', 'Guna'), ('Shivpuri', 'Shivpuri'), ('Unnao', 'Unnao'), ('Surendranagar', 'Surendranagar'), ('Balasore', 'Balasore'), ('Nabadwip', 'Nabadwip'), ('Bongaigaon', 'Bongaigaon'), ('Alappuzha', 'Alappuzha'), ('Alappuzha', 'Alappuzha'), ('Cuddalore', 'Cuddalore'), ('Hassan', 'Hassan'), ('Gadag', 'Gadag'), ('Shimla', 'Shimla'), ('Komarapalayam', 'Komarapalayam'), ('Bahadurgarh', 'Bahadurgarh'), ('Machilipatnam', 'Machilipatnam'), ('Midnapore', 'Midnapore'), ('Bharuch', 'Bharuch'), ('Hoshiarpur', 'Hoshiarpur'), ('Jaunpur', 'Jaunpur'), ('Adoni', 'Adoni'), ('Jind', 'Jind'), ('Udupi', 'Udupi'), ('Tonk', 'Tonk'), ('Tenali', 'Tenali'), ('Lakhimpur', 'Lakhimpur'), ('Balurghat', 'Balurghat'), ('Kanchipuram', 'Kanchipuram'), ('Vapi', 'Vapi'), ('Proddatur', 'Proddatur'), ('Ambur', 'Ambur'), ('Robertsonpet', 'Robertsonpet'), ('Hathras', 'Hathras'), ('Navsari', 'Navsari'), ('Banda', 'Banda'), ('Pilibhit', 'Pilibhit'), ('Mahbubnagar', 'Mahbubnagar'), ('Bettiah', 'Bettiah'), ('Vidisha', 'Vidisha'), ('Saharsa', 'Saharsa'), ('Kishangarh', 'Kishangarh'), ('Thanesar', 'Thanesar'), ('Barabanki', 'Barabanki'), ('Mughalsarai', 'Mughalsarai'), ('Veraval', 'Veraval'), ('Rudrapur', 'Rudrapur'), ('Chittorgarh', 'Chittorgarh'), ('Dibrugarh', 'Dibrugarh'), ('Chittoor', 'Chittoor'), ('Hazaribagh', 'Hazaribagh'), ('Jorhat', 'Jorhat'), ('Hindupur', 'Hindupur'), ('Porbandar', 'Porbandar'), ('Batala', 'Batala'), ('Beawar', 'Beawar'), ('Bhadravati', 'Bhadravati'), ('Hanumangarh', 'Hanumangarh'), ('Satara', 'Satara'), ('Chhatarpur', 'Chhatarpur'), ('Hajipur', 'Hajipur'), ('Damoh', 'Damoh'), ('Sasaram', 'Sasaram'), ('Nagaon', 'Nagaon'), ('Beed', 'Beed'), ('Mohali', 'Mohali'), ('Chitradurga', 'Chitradurga'), ('Tiruvannamalai', 'Tiruvannamalai'), ('Abohar', 'Abohar'), ('Harihar', 'Harihar'), ('Basirhat', 'Basirhat'), ('Kaithal', 'Kaithal'), ('Pudukkottai', 'Pudukkottai'), ('Godhra', 'Godhra'), ('Giridih', 'Giridih'), ('Pathankot', 'Pathankot'), ('Shillong', 'Shillong'), ('Bhuj', 'Bhuj'), ('Khurja', 'Khurja'), ('Bhimavaram', 'Bhimavaram'), ('Pakhanjore', 'Pakhanjore'), ('Mandsaur', 'Mandsaur'), ('Moga', 'Moga'), ('Rewari', 'Rewari'), ('Ankleshwar', 'Ankleshwar'), ('Kumbakonam', 'Kumbakonam'), ('Pandharpur', 'Pandharpur'), ('Gonda', 'Gonda'), ('Kolar', 'Kolar'), ('Yavatmal', 'Yavatmal'), ('Bankura', 'Bankura'), ('Mandya', 'Mandya'), ('Dehri', 'Dehri'), ('Kamptee', 'Kamptee'), ('Nalgonda', 'Nalgonda'), ('Madanapalle', 'Madanapalle'), ('Malerkotla', 'Malerkotla'), ('Siwan', 'Siwan'), ('Khargone', 'Khargone'), ('Mainpuri', 'Mainpuri'), ('Dholpur', 'Dholpur'), ('Lalitpur', 'Lalitpur'), ('Chakdaha', 'Chakdaha'), ('Gondia', 'Gondia'), ('Ramgarh', 'Ramgarh'), ('Darjeeling', 'Darjeeling'), ('Palwal', 'Palwal'), ('Etah', 'Etah'), ('Palakkad', 'Palakkad'), ('Rajapalayam', 'Rajapalayam'), ('Botad', 'Botad'), ('Gangapur', 'Gangapur'), ('Kottayam', 'Kottayam'), ('Deoria', 'Deoria'), ('Bhadrak', 'Bhadrak'), ('Neemuch', 'Neemuch'), ('Khanna', 'Khanna'), ('Alipurduar', 'Alipurduar'), ('Purulia', 'Purulia'), ('Guntakal', 'Guntakal'), ('Pithampur', 'Pithampur'), ('Ujhani', 'Ujhani'), ('Srikakulam', 'Srikakulam'), ('Tinsukia', 'Tinsukia'), ('Patan', 'Patan'), ('Jagdalpur', 'Jagdalpur'), ('Motihari', 'Motihari'), ('Jangipur', 'Jangipur'), ('Palanpur', 'Palanpur'), ('Dharmavaram', 'Dharmavaram'), ('Kashipur', 'Kashipur'), ('Ghazipur', 'Ghazipur'), ('Sawai Madhopur', 'Sawai Madhopur'), ('Churu', 'Churu'), ('Medininagar', 'Medininagar'), ('Dahod', 'Dahod'), ('Chirkunda', 'Chirkunda'), ('Nawada', 'Nawada'), ('Chikkamagallooru', 'Chikkamagallooru'), ('Chikmagalur', 'Chikmagalur'), ('Jetpur', 'Jetpur'), ('Gudivada', 'Gudivada'), ('Baran', 'Baran'), ('Hoshangabad', 'Hoshangabad'), ('Adilabad', 'Adilabad'), ('Muktasar', 'Muktasar'), ('Baripada', 'Baripada'), ('Hosur', 'Hosur'), ('Barnala', 'Barnala'), ('Makrana', 'Makrana'), ('Narasaraopet', 'Narasaraopet'), ('Sultanpur', 'Sultanpur'), ('Azamgarh', 'Azamgarh'), ('Bijnor', 'Bijnor'), ('Sahaswan', 'Sahaswan'), ('Basti', 'Basti'), ('Gangawati', 'Gangawati'), ('Kothamangalam', 'Kothamangalam'), ('Valsad', 'Valsad'), ('Ambikapur', 'Ambikapur'), ('Itarsi', 'Itarsi'), ('Panaji', 'Panaji'), ('Chandausi', 'Chandausi'), ('Siddipet', 'Siddipet'), ('Kalol', 'Kalol'), ('Bagaha', 'Bagaha'), ('Achalpur', 'Achalpur'), ('Gondal', 'Gondal'), ('Osmanabad', 'Osmanabad'), ('Akbarpur', 'Akbarpur'), ('Ballia', 'Ballia'), ('Deesa', 'Deesa'), ('Nagaur', 'Nagaur'), ('Bangaon', 'Bangaon'), ('Buxar', 'Buxar'), ('Firozpur', 'Firozpur'), ('Hindaun', 'Hindaun'), ('Mubarakpur', 'Mubarakpur'), ('Tanda', 'Tanda'), ('Dhubri', 'Dhubri'), ('Sehore', 'Sehore'), ('Anantnag', 'Anantnag'), ('Tadipatri', 'Tadipatri'), ('Port Blair', 'Port Blair'), ('Greater Noida', 'Greater Noida'), ('Shikohabad', 'Shikohabad'), ('Shamli', 'Shamli'), ('Kishanganj', 'Kishanganj'), ('Hinganghat', 'Hinganghat'), ('Cooch Behar', 'Cooch Behar'), ('Karaikudi', 'Karaikudi'), ('Wardha', 'Wardha'), ('Ranebennuru', 'Ranebennuru'), ('Sitamarhi', 'Sitamarhi'), ('Neyveli', 'Neyveli'), ('Amreli', 'Amreli'), ('Amreli', 'Amreli'), ('Suryapet', 'Suryapet'), ('Jamalpur', 'Jamalpur'), ('Bhiwadi', 'Bhiwadi'), ('Barshi', 'Barshi'), ('Bundi', 'Bundi'), ('Tadepalligudem', 'Tadepalligudem'), ('Miryalaguda', 'Miryalaguda'), ('Chirmiri', 'Chirmiri'), ('Betul', 'Betul'), ('Amaravati', 'Amaravati'), ('Nagapattinam', 'Nagapattinam'), ('Baraut', 'Baraut'), ('Jehanabad', 'Jehanabad'), ('Seoni', 'Seoni'), ('Rishikesh', 'Rishikesh'), ('Khair', 'Khair'), ('Dhamtari', 'Dhamtari'), ('Kapurthala', 'Kapurthala'), ('Sujangarh', 'Sujangarh'), ('Aurangabad', 'Aurangabad'), ('Chilakaluripet', 'Chilakaluripet'), ('Malappuram', 'Malappuram'), ('Kasganj', 'Kasganj'), ('Vasco', 'Vasco'), ('Tezpur', 'Tezpur'), ('Jhunjhunu', 'Jhunjhunu'), ('Datia', 'Datia'), ('Banswara', 'Banswara'), ('Raigarh', 'Raigarh'), ('Nagda', 'Nagda'), ('Lakhisarai', 'Lakhisarai'), ('Auraiya', 'Auraiya'), ('Kohima', 'Kohima'), ('Gangtok', 'Gangtok'), ('Mahuva', 'Mahuva'), ('Silvassa', 'Silvassa'), ('Balangir', 'Balangir'), ('Phagwara', 'Phagwara'), ('Jharsuguda', 'Jharsuguda'), ('Chalisgaon', 'Chalisgaon'), ('Khatauli', 'Khatauli'), ('Manjeri', 'Manjeri'), ('Mormugao', 'Mormugao'), ('Deoband', 'Deoband'), ('Mahasamund', 'Mahasamund'), ('Jagtial', 'Jagtial'), ('Viluppuram', 'Viluppuram'), ('Amalner', 'Amalner'), ('Sardarshahar', 'Sardarshahar'), ('Paramakudi', 'Paramakudi'), ('Zirakpur', 'Zirakpur'), ('Tiruchengode', 'Tiruchengode'), ('Nagina', 'Nagina'), ('Mahoba', 'Mahoba'), ('Muradnagar', 'Muradnagar'), ('Ramanagara', 'Ramanagara'), ('Kovilpatti', 'Kovilpatti'), ('Dhanpuri', 'Dhanpuri'), ('Bhadohi', 'Bhadohi'), ('Theni-Allinagaram', 'Theni-Allinagaram'), ('Khamgaon', 'Khamgaon'), ('Dhar', 'Dhar'), ('Balaghat', 'Balaghat'), ('Akot', 'Akot'), ('Fatehpur', 'Fatehpur'), ('Thalassery', 'Thalassery'), ('Bolpur', 'Bolpur'), ('Kanthi', 'Kanthi'), ('Rajpura', 'Rajpura'), ('Udgir', 'Udgir'), ('Bhandara', 'Bhandara'), ('Dadri', 'Dadri'), ('Ponnani', 'Ponnani'), ('Kadayanallur', 'Kadayanallur'), ('Pratapgarh', 'Pratapgarh'), ('Pollachi', 'Pollachi'), ('Najibabad', 'Najibabad'), ('Parli', 'Parli'), ('Ooty', 'Ooty'), ('Jhumri Telaiya', 'Jhumri Telaiya'), ('Margao', 'Margao'), ('Mancherial', 'Mancherial'), ('Karaikal', 'Karaikal'), ('Dausa', 'Dausa'), ('Jeypore', 'Jeypore'), ('Mehsana', 'Mehsana'), ('Karauli', 'Karauli'), ('Sahibganj', 'Sahibganj'), ('Kothagudem', 'Kothagudem'), ('Itanagar', 'Itanagar'), ('Bagalkot', 'Bagalkot'), ('Kavaratti', 'Kavaratti')], max_length=500, null=True)),
                ('factory_state', models.CharField(blank=True, choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Chandigarh', 'Chandigarh'), ('Dadra and Nagar Haveli', 'Dadra and Nagar Haveli'), ('Daman and Diu', 'Daman and Diu'), ('Lakshadweep', 'Lakshadweep'), ('Delhi', 'Delhi'), ('Puducherry', 'Puducherry')], max_length=500, null=True)),
                ('factory_pan', models.CharField(blank=True, max_length=500, null=True)),
                ('factory_gst', models.CharField(blank=True, max_length=500, null=True)),
                ('region', models.CharField(blank=True, max_length=500, null=True)),
                ('master_category', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='New_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(blank=True, null=True)),
                ('order_no', models.CharField(blank=True, max_length=100, null=True)),
                ('total_qty', models.IntegerField(blank=True, null=True)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('del_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.userprofile')),
                ('drop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.drop')),
            ],
        ),
        migrations.CreateModel(
            name='Onoff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_date', models.DateField(blank=True, null=True)),
                ('order_no', models.CharField(blank=True, max_length=100, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('buyer_del_date', models.DateField(blank=True, null=True)),
                ('supplier_del_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.userprofile')),
                ('drop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.drop')),
            ],
        ),
        migrations.CreateModel(
            name='Order_Management',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order_Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pi_date', models.DateField(blank=True, null=True)),
                ('pi_no', models.IntegerField(blank=True, default=0, null=True)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('buyer_del_date', models.DateField(blank=True, null=True)),
                ('supplier_del_date', models.DateField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.order')),
            ],
        ),
        migrations.CreateModel(
            name='Quality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('count', models.CharField(blank=True, max_length=100, null=True)),
                ('construction', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.CharField(blank=True, max_length=100, null=True)),
                ('gsm', models.CharField(blank=True, max_length=100, null=True)),
                ('width', models.CharField(blank=True, max_length=100, null=True)),
                ('s_price', models.CharField(blank=True, max_length=100, null=True)),
                ('r_price', models.CharField(blank=True, max_length=100, null=True)),
                ('d_price', models.CharField(blank=True, max_length=100, null=True)),
                ('moq', models.CharField(blank=True, max_length=100, null=True)),
                ('lead_time', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('desc', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Travel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor_name', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor_owner', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('vendor_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor_address', models.CharField(blank=True, max_length=500, null=True)),
                ('vendor_city', models.CharField(blank=True, choices=[('Delhi', 'Delhi'), ('Kolkata', 'Kolkata'), ('Mumbai', 'Mumbai'), ('Hyderabad', 'Hyderabad'), ('Bengaluru', 'Bengaluru'), ('Chennai', 'Chennai'), ('Ahmedabad', 'Ahmedabad'), ('Surat', 'Surat'), ('Pune', 'Pune'), ('Jaipur', 'Jaipur'), ('Kanpur', 'Kanpur'), ('Lucknow', 'Lucknow'), ('Nagpur', 'Nagpur'), ('Ghaziabad', 'Ghaziabad'), ('Indore', 'Indore'), ('Coimbatore', 'Coimbatore'), ('Patna', 'Patna'), ('Visakhapatnam', 'Visakhapatnam'), ('Bhopal', 'Bhopal'), ('Nashik', 'Nashik'), ('Pimpri-Chinchwad', 'Pimpri-Chinchwad'), ('Agra', 'Agra'), ('Vadodara', 'Vadodara'), ('Ludhiana', 'Ludhiana'), ('Madurai', 'Madurai'), ('Varanasi', 'Varanasi'), ('Meerut', 'Meerut'), ('Faridabad', 'Faridabad'), ('Jamshedpur', 'Jamshedpur'), ('Rajkot', 'Rajkot'), ('Jabalpur', 'Jabalpur'), ('Asansol', 'Asansol'), ('Allahabad', 'Allahabad'), ('Dhanbad', 'Dhanbad'), ('Srinagar', 'Srinagar'), ('Aurangabad', 'Aurangabad'), ('Jodhpur', 'Jodhpur'), ('Amritsar', 'Amritsar'), ('Ranchi', 'Ranchi'), ('Gwalior', 'Gwalior'), ('Chandigarh', 'Chandigarh'), ('Vijayawada', 'Vijayawada'), ('Tiruchirappalli', 'Tiruchirappalli'), ('Raipur', 'Raipur'), ('Kota', 'Kota'), ('Bareilly', 'Bareilly'), ('Guwahati', 'Guwahati'), ('Tirupur', 'Tirupur'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Solapur', 'Solapur'), ('Hubli', 'Hubli'), ('Salem', 'Salem'), ('Aligarh', 'Aligarh'), ('Gurgaon', 'Gurgaon'), ('Durg', 'Durg'), ('Moradabad', 'Moradabad'), ('Mysore', 'Mysore'), ('Bhubaneswar', 'Bhubaneswar'), ('Jalandhar', 'Jalandhar'), ('Warangal', 'Warangal'), ('Guntur', 'Guntur'), ('Dehradun', 'Dehradun'), ('Bhiwandi', 'Bhiwandi'), ('Saharanpur', 'Saharanpur'), ('Siliguri', 'Siliguri'), ('Gorakhpur', 'Gorakhpur'), ('Cuttack', 'Cuttack'), ('Pondicherry', 'Pondicherry'), ('Amravati', 'Amravati'), ('Bikaner', 'Bikaner'), ('Faizabad', 'Faizabad'), ('Kochi', 'Kochi'), ('Firozabad', 'Firozabad'), ('Bhavnagar', 'Bhavnagar'), ('Durgapur', 'Durgapur'), ('Bokaro Steel City', 'Bokaro Steel City'), ('Naya Raipur', 'Naya Raipur'), ('Rourkela', 'Rourkela'), ('Ajmer', 'Ajmer'), ('Nanded', 'Nanded'), ('Kolhapur', 'Kolhapur'), ('Jhansi', 'Jhansi'), ('Gulbarga', 'Gulbarga'), ('Agartala', 'Agartala'), ('Erode', 'Erode'), ('Ujjain', 'Ujjain'), ('Sangli-Miraj-Kupwad', 'Sangli-Miraj-Kupwad'), ('Jammu', 'Jammu'), ('Nellore', 'Nellore'), ('Mangalore', 'Mangalore'), ('Tirunelveli', 'Tirunelveli'), ('Muzaffarnagar', 'Muzaffarnagar'), ('Belgaum', 'Belgaum'), ('Vellore', 'Vellore'), ('Jamnagar', 'Jamnagar'), ('Udaipur', 'Udaipur'), ('Gaya', 'Gaya'), ('Jalgaon', 'Jalgaon'), ('Mathura', 'Mathura'), ('Patiala', 'Patiala'), ('Panipat', 'Panipat'), ('Davangere', 'Davangere'), ('Calicut', 'Calicut'), ('Akola', 'Akola'), ('Kurnool', 'Kurnool'), ('Rajamahendravaram', 'Rajamahendravaram'), ('Latur', 'Latur'), ('Tuticorin', 'Tuticorin'), ('Bhagalpur', 'Bhagalpur'), ('Malegaon', 'Malegaon'), ('Bellary', 'Bellary'), ('Ambala', 'Ambala'), ('Muzaffarpur', 'Muzaffarpur'), ('Yamunanagar', 'Yamunanagar'), ('Dhule', 'Dhule'), ('Dimapur', 'Dimapur'), ('Tirupati', 'Tirupati'), ('Rohtak', 'Rohtak'), ('Sagar', 'Sagar'), ('Budaun', 'Budaun'), ('Korba', 'Korba'), ('Bhilwara', 'Bhilwara'), ('Rampur', 'Rampur'), ('Shahjahanpur', 'Shahjahanpur'), ('Berhampur', 'Berhampur'), ('Ahmednagar', 'Ahmednagar'), ('Kollam', 'Kollam'), ('Bardhaman', 'Bardhaman'), ('Kadapa', 'Kadapa'), ('Alwar', 'Alwar'), ('Bilaspur', 'Bilaspur'), ('Nandurbar', 'Nandurbar'), ('Bijapur', 'Bijapur'), ('Ichalkaranji', 'Ichalkaranji'), ('Thrissur', 'Thrissur'), ('Chandrapur', 'Chandrapur'), ('Malda', 'Malda'), ('Shimoga', 'Shimoga'), ('Junagadh', 'Junagadh'), ('Farrukhabad', 'Farrukhabad'), ('Kakinada', 'Kakinada'), ('Nizamabad', 'Nizamabad'), ('Purnia', 'Purnia'), ('Haridwar', 'Haridwar'), ('Hisar', 'Hisar'), ('Darbhanga', 'Darbhanga'), ('Tumkur', 'Tumkur'), ('Baharampur', 'Baharampur'), ('Habra', 'Habra'), ('Jalpaiguri', 'Jalpaiguri'), ('Karnal', 'Karnal'), ('Ozhukarai', 'Ozhukarai'), ('Bihar Sharif', 'Bihar Sharif'), ('Kharagpur', 'Kharagpur'), ('Aizawl', 'Aizawl'), ('Sonipat', 'Sonipat'), ('Gudiyatham', 'Gudiyatham'), ('Dewas', 'Dewas'), ('Shantipur', 'Shantipur'), ('Bathinda', 'Bathinda'), ('Jalna', 'Jalna'), ('Satna', 'Satna'), ('Mau', 'Mau'), ('Roorkee', 'Roorkee'), ('Ratlam', 'Ratlam'), ('Parbhani', 'Parbhani'), ('Sambalpur', 'Sambalpur'), ('Anantapur', 'Anantapur'), ('Imphal', 'Imphal'), ('Rajnandgaon', 'Rajnandgaon'), ('Hapur', 'Hapur'), ('Karimnagar', 'Karimnagar'), ('Arrah', 'Arrah'), ('Noida', 'Noida'), ('Etawah', 'Etawah'), ('Haldwani', 'Haldwani'), ('Bharatpur', 'Bharatpur'), ('Begusarai', 'Begusarai'), ('Sri Ganganagar', 'Sri Ganganagar'), ('Dankuni', 'Dankuni'), ('Gandhidham', 'Gandhidham'), ('Mirzapur', 'Mirzapur'), ('Sikar', 'Sikar'), ('Katihar', 'Katihar'), ('Dhulian', 'Dhulian'), ('Ranaghat', 'Ranaghat'), ('Rewa', 'Rewa'), ('Bulandshahr', 'Bulandshahr'), ('Kannur', 'Kannur'), ('Raichur', 'Raichur'), ('Pali', 'Pali'), ('Ramagundam', 'Ramagundam'), ('Silchar', 'Silchar'), ('Vizianagaram', 'Vizianagaram'), ('Nagercoil', 'Nagercoil'), ('Thanjavur', 'Thanjavur'), ('Katni', 'Katni'), ('Sambhal', 'Sambhal'), ('Singrauli', 'Singrauli'), ('Nadiad', 'Nadiad'), ('Eluru', 'Eluru'), ('Bidar', 'Bidar'), ('Munger', 'Munger'), ('Chhapra', 'Chhapra'), ('Burhanpur', 'Burhanpur'), ('Panchkula', 'Panchkula'), ('Dindigul', 'Dindigul'), ('Gandhinagar', 'Gandhinagar'), ('Hospet', 'Hospet'), ('Bhusawal', 'Bhusawal'), ('Deoghar', 'Deoghar'), ('Ongole', 'Ongole'), ('Puri', 'Puri'), ('Haldia', 'Haldia'), ('Nandyal', 'Nandyal'), ('Khandwa', 'Khandwa'), ('Morena', 'Morena'), ('Raiganj', 'Raiganj'), ('Anand', 'Anand'), ('Bhiwani', 'Bhiwani'), ('Bhind', 'Bhind'), ('Amroha', 'Amroha'), ('Hardoi', 'Hardoi'), ('Vaniyambadi', 'Vaniyambadi'), ('Morbi', 'Morbi'), ('Fatehpur', 'Fatehpur'), ('Kasaragod', 'Kasaragod'), ('Raebareli', 'Raebareli'), ('Daman', 'Daman'), ('Orai', 'Orai'), ('Chhindwara', 'Chhindwara'), ('Barmer', 'Barmer'), ('Sitapur', 'Sitapur'), ('Bahraich', 'Bahraich'), ('Phusro', 'Phusro'), ('Khammam', 'Khammam'), ('Khambhat', 'Khambhat'), ('Sirsa', 'Sirsa'), ('Modinagar', 'Modinagar'), ('Krishnanagar', 'Krishnanagar'), ('Guna', 'Guna'), ('Shivpuri', 'Shivpuri'), ('Unnao', 'Unnao'), ('Surendranagar', 'Surendranagar'), ('Balasore', 'Balasore'), ('Nabadwip', 'Nabadwip'), ('Bongaigaon', 'Bongaigaon'), ('Alappuzha', 'Alappuzha'), ('Alappuzha', 'Alappuzha'), ('Cuddalore', 'Cuddalore'), ('Hassan', 'Hassan'), ('Gadag', 'Gadag'), ('Shimla', 'Shimla'), ('Komarapalayam', 'Komarapalayam'), ('Bahadurgarh', 'Bahadurgarh'), ('Machilipatnam', 'Machilipatnam'), ('Midnapore', 'Midnapore'), ('Bharuch', 'Bharuch'), ('Hoshiarpur', 'Hoshiarpur'), ('Jaunpur', 'Jaunpur'), ('Adoni', 'Adoni'), ('Jind', 'Jind'), ('Udupi', 'Udupi'), ('Tonk', 'Tonk'), ('Tenali', 'Tenali'), ('Lakhimpur', 'Lakhimpur'), ('Balurghat', 'Balurghat'), ('Kanchipuram', 'Kanchipuram'), ('Vapi', 'Vapi'), ('Proddatur', 'Proddatur'), ('Ambur', 'Ambur'), ('Robertsonpet', 'Robertsonpet'), ('Hathras', 'Hathras'), ('Navsari', 'Navsari'), ('Banda', 'Banda'), ('Pilibhit', 'Pilibhit'), ('Mahbubnagar', 'Mahbubnagar'), ('Bettiah', 'Bettiah'), ('Vidisha', 'Vidisha'), ('Saharsa', 'Saharsa'), ('Kishangarh', 'Kishangarh'), ('Thanesar', 'Thanesar'), ('Barabanki', 'Barabanki'), ('Mughalsarai', 'Mughalsarai'), ('Veraval', 'Veraval'), ('Rudrapur', 'Rudrapur'), ('Chittorgarh', 'Chittorgarh'), ('Dibrugarh', 'Dibrugarh'), ('Chittoor', 'Chittoor'), ('Hazaribagh', 'Hazaribagh'), ('Jorhat', 'Jorhat'), ('Hindupur', 'Hindupur'), ('Porbandar', 'Porbandar'), ('Batala', 'Batala'), ('Beawar', 'Beawar'), ('Bhadravati', 'Bhadravati'), ('Hanumangarh', 'Hanumangarh'), ('Satara', 'Satara'), ('Chhatarpur', 'Chhatarpur'), ('Hajipur', 'Hajipur'), ('Damoh', 'Damoh'), ('Sasaram', 'Sasaram'), ('Nagaon', 'Nagaon'), ('Beed', 'Beed'), ('Mohali', 'Mohali'), ('Chitradurga', 'Chitradurga'), ('Tiruvannamalai', 'Tiruvannamalai'), ('Abohar', 'Abohar'), ('Harihar', 'Harihar'), ('Basirhat', 'Basirhat'), ('Kaithal', 'Kaithal'), ('Pudukkottai', 'Pudukkottai'), ('Godhra', 'Godhra'), ('Giridih', 'Giridih'), ('Pathankot', 'Pathankot'), ('Shillong', 'Shillong'), ('Bhuj', 'Bhuj'), ('Khurja', 'Khurja'), ('Bhimavaram', 'Bhimavaram'), ('Pakhanjore', 'Pakhanjore'), ('Mandsaur', 'Mandsaur'), ('Moga', 'Moga'), ('Rewari', 'Rewari'), ('Ankleshwar', 'Ankleshwar'), ('Kumbakonam', 'Kumbakonam'), ('Pandharpur', 'Pandharpur'), ('Gonda', 'Gonda'), ('Kolar', 'Kolar'), ('Yavatmal', 'Yavatmal'), ('Bankura', 'Bankura'), ('Mandya', 'Mandya'), ('Dehri', 'Dehri'), ('Kamptee', 'Kamptee'), ('Nalgonda', 'Nalgonda'), ('Madanapalle', 'Madanapalle'), ('Malerkotla', 'Malerkotla'), ('Siwan', 'Siwan'), ('Khargone', 'Khargone'), ('Mainpuri', 'Mainpuri'), ('Dholpur', 'Dholpur'), ('Lalitpur', 'Lalitpur'), ('Chakdaha', 'Chakdaha'), ('Gondia', 'Gondia'), ('Ramgarh', 'Ramgarh'), ('Darjeeling', 'Darjeeling'), ('Palwal', 'Palwal'), ('Etah', 'Etah'), ('Palakkad', 'Palakkad'), ('Rajapalayam', 'Rajapalayam'), ('Botad', 'Botad'), ('Gangapur', 'Gangapur'), ('Kottayam', 'Kottayam'), ('Deoria', 'Deoria'), ('Bhadrak', 'Bhadrak'), ('Neemuch', 'Neemuch'), ('Khanna', 'Khanna'), ('Alipurduar', 'Alipurduar'), ('Purulia', 'Purulia'), ('Guntakal', 'Guntakal'), ('Pithampur', 'Pithampur'), ('Ujhani', 'Ujhani'), ('Srikakulam', 'Srikakulam'), ('Tinsukia', 'Tinsukia'), ('Patan', 'Patan'), ('Jagdalpur', 'Jagdalpur'), ('Motihari', 'Motihari'), ('Jangipur', 'Jangipur'), ('Palanpur', 'Palanpur'), ('Dharmavaram', 'Dharmavaram'), ('Kashipur', 'Kashipur'), ('Ghazipur', 'Ghazipur'), ('Sawai Madhopur', 'Sawai Madhopur'), ('Churu', 'Churu'), ('Medininagar', 'Medininagar'), ('Dahod', 'Dahod'), ('Chirkunda', 'Chirkunda'), ('Nawada', 'Nawada'), ('Chikkamagallooru', 'Chikkamagallooru'), ('Chikmagalur', 'Chikmagalur'), ('Jetpur', 'Jetpur'), ('Gudivada', 'Gudivada'), ('Baran', 'Baran'), ('Hoshangabad', 'Hoshangabad'), ('Adilabad', 'Adilabad'), ('Muktasar', 'Muktasar'), ('Baripada', 'Baripada'), ('Hosur', 'Hosur'), ('Barnala', 'Barnala'), ('Makrana', 'Makrana'), ('Narasaraopet', 'Narasaraopet'), ('Sultanpur', 'Sultanpur'), ('Azamgarh', 'Azamgarh'), ('Bijnor', 'Bijnor'), ('Sahaswan', 'Sahaswan'), ('Basti', 'Basti'), ('Gangawati', 'Gangawati'), ('Kothamangalam', 'Kothamangalam'), ('Valsad', 'Valsad'), ('Ambikapur', 'Ambikapur'), ('Itarsi', 'Itarsi'), ('Panaji', 'Panaji'), ('Chandausi', 'Chandausi'), ('Siddipet', 'Siddipet'), ('Kalol', 'Kalol'), ('Bagaha', 'Bagaha'), ('Achalpur', 'Achalpur'), ('Gondal', 'Gondal'), ('Osmanabad', 'Osmanabad'), ('Akbarpur', 'Akbarpur'), ('Ballia', 'Ballia'), ('Deesa', 'Deesa'), ('Nagaur', 'Nagaur'), ('Bangaon', 'Bangaon'), ('Buxar', 'Buxar'), ('Firozpur', 'Firozpur'), ('Hindaun', 'Hindaun'), ('Mubarakpur', 'Mubarakpur'), ('Tanda', 'Tanda'), ('Dhubri', 'Dhubri'), ('Sehore', 'Sehore'), ('Anantnag', 'Anantnag'), ('Tadipatri', 'Tadipatri'), ('Port Blair', 'Port Blair'), ('Greater Noida', 'Greater Noida'), ('Shikohabad', 'Shikohabad'), ('Shamli', 'Shamli'), ('Kishanganj', 'Kishanganj'), ('Hinganghat', 'Hinganghat'), ('Cooch Behar', 'Cooch Behar'), ('Karaikudi', 'Karaikudi'), ('Wardha', 'Wardha'), ('Ranebennuru', 'Ranebennuru'), ('Sitamarhi', 'Sitamarhi'), ('Neyveli', 'Neyveli'), ('Amreli', 'Amreli'), ('Amreli', 'Amreli'), ('Suryapet', 'Suryapet'), ('Jamalpur', 'Jamalpur'), ('Bhiwadi', 'Bhiwadi'), ('Barshi', 'Barshi'), ('Bundi', 'Bundi'), ('Tadepalligudem', 'Tadepalligudem'), ('Miryalaguda', 'Miryalaguda'), ('Chirmiri', 'Chirmiri'), ('Betul', 'Betul'), ('Amaravati', 'Amaravati'), ('Nagapattinam', 'Nagapattinam'), ('Baraut', 'Baraut'), ('Jehanabad', 'Jehanabad'), ('Seoni', 'Seoni'), ('Rishikesh', 'Rishikesh'), ('Khair', 'Khair'), ('Dhamtari', 'Dhamtari'), ('Kapurthala', 'Kapurthala'), ('Sujangarh', 'Sujangarh'), ('Aurangabad', 'Aurangabad'), ('Chilakaluripet', 'Chilakaluripet'), ('Malappuram', 'Malappuram'), ('Kasganj', 'Kasganj'), ('Vasco', 'Vasco'), ('Tezpur', 'Tezpur'), ('Jhunjhunu', 'Jhunjhunu'), ('Datia', 'Datia'), ('Banswara', 'Banswara'), ('Raigarh', 'Raigarh'), ('Nagda', 'Nagda'), ('Lakhisarai', 'Lakhisarai'), ('Auraiya', 'Auraiya'), ('Kohima', 'Kohima'), ('Gangtok', 'Gangtok'), ('Mahuva', 'Mahuva'), ('Silvassa', 'Silvassa'), ('Balangir', 'Balangir'), ('Phagwara', 'Phagwara'), ('Jharsuguda', 'Jharsuguda'), ('Chalisgaon', 'Chalisgaon'), ('Khatauli', 'Khatauli'), ('Manjeri', 'Manjeri'), ('Mormugao', 'Mormugao'), ('Deoband', 'Deoband'), ('Mahasamund', 'Mahasamund'), ('Jagtial', 'Jagtial'), ('Viluppuram', 'Viluppuram'), ('Amalner', 'Amalner'), ('Sardarshahar', 'Sardarshahar'), ('Paramakudi', 'Paramakudi'), ('Zirakpur', 'Zirakpur'), ('Tiruchengode', 'Tiruchengode'), ('Nagina', 'Nagina'), ('Mahoba', 'Mahoba'), ('Muradnagar', 'Muradnagar'), ('Ramanagara', 'Ramanagara'), ('Kovilpatti', 'Kovilpatti'), ('Dhanpuri', 'Dhanpuri'), ('Bhadohi', 'Bhadohi'), ('Theni-Allinagaram', 'Theni-Allinagaram'), ('Khamgaon', 'Khamgaon'), ('Dhar', 'Dhar'), ('Balaghat', 'Balaghat'), ('Akot', 'Akot'), ('Fatehpur', 'Fatehpur'), ('Thalassery', 'Thalassery'), ('Bolpur', 'Bolpur'), ('Kanthi', 'Kanthi'), ('Rajpura', 'Rajpura'), ('Udgir', 'Udgir'), ('Bhandara', 'Bhandara'), ('Dadri', 'Dadri'), ('Ponnani', 'Ponnani'), ('Kadayanallur', 'Kadayanallur'), ('Pratapgarh', 'Pratapgarh'), ('Pollachi', 'Pollachi'), ('Najibabad', 'Najibabad'), ('Parli', 'Parli'), ('Ooty', 'Ooty'), ('Jhumri Telaiya', 'Jhumri Telaiya'), ('Margao', 'Margao'), ('Mancherial', 'Mancherial'), ('Karaikal', 'Karaikal'), ('Dausa', 'Dausa'), ('Jeypore', 'Jeypore'), ('Mehsana', 'Mehsana'), ('Karauli', 'Karauli'), ('Sahibganj', 'Sahibganj'), ('Kothagudem', 'Kothagudem'), ('Itanagar', 'Itanagar'), ('Bagalkot', 'Bagalkot'), ('Kavaratti', 'Kavaratti')], max_length=500, null=True)),
                ('vendor_state', models.CharField(blank=True, choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Chandigarh', 'Chandigarh'), ('Dadra and Nagar Haveli', 'Dadra and Nagar Haveli'), ('Daman and Diu', 'Daman and Diu'), ('Lakshadweep', 'Lakshadweep'), ('Delhi', 'Delhi'), ('Puducherry', 'Puducherry')], max_length=500, null=True)),
                ('vendor_pan', models.CharField(blank=True, max_length=500, null=True)),
                ('vendor_gst', models.CharField(blank=True, max_length=500, null=True)),
                ('factory_type', models.CharField(blank=True, choices=[('Factory', 'Factory'), ('Packaging Unit', 'Packaging Unit'), ('Mill', 'Mill')], max_length=50, null=True)),
                ('factory_name', models.CharField(blank=True, max_length=100, null=True)),
                ('factory_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('factory_contact', models.CharField(blank=True, max_length=100, null=True)),
                ('factory_address', models.CharField(blank=True, max_length=500, null=True)),
                ('factory_city', models.CharField(blank=True, choices=[('Delhi', 'Delhi'), ('Kolkata', 'Kolkata'), ('Mumbai', 'Mumbai'), ('Hyderabad', 'Hyderabad'), ('Bengaluru', 'Bengaluru'), ('Chennai', 'Chennai'), ('Ahmedabad', 'Ahmedabad'), ('Surat', 'Surat'), ('Pune', 'Pune'), ('Jaipur', 'Jaipur'), ('Kanpur', 'Kanpur'), ('Lucknow', 'Lucknow'), ('Nagpur', 'Nagpur'), ('Ghaziabad', 'Ghaziabad'), ('Indore', 'Indore'), ('Coimbatore', 'Coimbatore'), ('Patna', 'Patna'), ('Visakhapatnam', 'Visakhapatnam'), ('Bhopal', 'Bhopal'), ('Nashik', 'Nashik'), ('Pimpri-Chinchwad', 'Pimpri-Chinchwad'), ('Agra', 'Agra'), ('Vadodara', 'Vadodara'), ('Ludhiana', 'Ludhiana'), ('Madurai', 'Madurai'), ('Varanasi', 'Varanasi'), ('Meerut', 'Meerut'), ('Faridabad', 'Faridabad'), ('Jamshedpur', 'Jamshedpur'), ('Rajkot', 'Rajkot'), ('Jabalpur', 'Jabalpur'), ('Asansol', 'Asansol'), ('Allahabad', 'Allahabad'), ('Dhanbad', 'Dhanbad'), ('Srinagar', 'Srinagar'), ('Aurangabad', 'Aurangabad'), ('Jodhpur', 'Jodhpur'), ('Amritsar', 'Amritsar'), ('Ranchi', 'Ranchi'), ('Gwalior', 'Gwalior'), ('Chandigarh', 'Chandigarh'), ('Vijayawada', 'Vijayawada'), ('Tiruchirappalli', 'Tiruchirappalli'), ('Raipur', 'Raipur'), ('Kota', 'Kota'), ('Bareilly', 'Bareilly'), ('Guwahati', 'Guwahati'), ('Tirupur', 'Tirupur'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Solapur', 'Solapur'), ('Hubli', 'Hubli'), ('Salem', 'Salem'), ('Aligarh', 'Aligarh'), ('Gurgaon', 'Gurgaon'), ('Durg', 'Durg'), ('Moradabad', 'Moradabad'), ('Mysore', 'Mysore'), ('Bhubaneswar', 'Bhubaneswar'), ('Jalandhar', 'Jalandhar'), ('Warangal', 'Warangal'), ('Guntur', 'Guntur'), ('Dehradun', 'Dehradun'), ('Bhiwandi', 'Bhiwandi'), ('Saharanpur', 'Saharanpur'), ('Siliguri', 'Siliguri'), ('Gorakhpur', 'Gorakhpur'), ('Cuttack', 'Cuttack'), ('Pondicherry', 'Pondicherry'), ('Amravati', 'Amravati'), ('Bikaner', 'Bikaner'), ('Faizabad', 'Faizabad'), ('Kochi', 'Kochi'), ('Firozabad', 'Firozabad'), ('Bhavnagar', 'Bhavnagar'), ('Durgapur', 'Durgapur'), ('Bokaro Steel City', 'Bokaro Steel City'), ('Naya Raipur', 'Naya Raipur'), ('Rourkela', 'Rourkela'), ('Ajmer', 'Ajmer'), ('Nanded', 'Nanded'), ('Kolhapur', 'Kolhapur'), ('Jhansi', 'Jhansi'), ('Gulbarga', 'Gulbarga'), ('Agartala', 'Agartala'), ('Erode', 'Erode'), ('Ujjain', 'Ujjain'), ('Sangli-Miraj-Kupwad', 'Sangli-Miraj-Kupwad'), ('Jammu', 'Jammu'), ('Nellore', 'Nellore'), ('Mangalore', 'Mangalore'), ('Tirunelveli', 'Tirunelveli'), ('Muzaffarnagar', 'Muzaffarnagar'), ('Belgaum', 'Belgaum'), ('Vellore', 'Vellore'), ('Jamnagar', 'Jamnagar'), ('Udaipur', 'Udaipur'), ('Gaya', 'Gaya'), ('Jalgaon', 'Jalgaon'), ('Mathura', 'Mathura'), ('Patiala', 'Patiala'), ('Panipat', 'Panipat'), ('Davangere', 'Davangere'), ('Calicut', 'Calicut'), ('Akola', 'Akola'), ('Kurnool', 'Kurnool'), ('Rajamahendravaram', 'Rajamahendravaram'), ('Latur', 'Latur'), ('Tuticorin', 'Tuticorin'), ('Bhagalpur', 'Bhagalpur'), ('Malegaon', 'Malegaon'), ('Bellary', 'Bellary'), ('Ambala', 'Ambala'), ('Muzaffarpur', 'Muzaffarpur'), ('Yamunanagar', 'Yamunanagar'), ('Dhule', 'Dhule'), ('Dimapur', 'Dimapur'), ('Tirupati', 'Tirupati'), ('Rohtak', 'Rohtak'), ('Sagar', 'Sagar'), ('Budaun', 'Budaun'), ('Korba', 'Korba'), ('Bhilwara', 'Bhilwara'), ('Rampur', 'Rampur'), ('Shahjahanpur', 'Shahjahanpur'), ('Berhampur', 'Berhampur'), ('Ahmednagar', 'Ahmednagar'), ('Kollam', 'Kollam'), ('Bardhaman', 'Bardhaman'), ('Kadapa', 'Kadapa'), ('Alwar', 'Alwar'), ('Bilaspur', 'Bilaspur'), ('Nandurbar', 'Nandurbar'), ('Bijapur', 'Bijapur'), ('Ichalkaranji', 'Ichalkaranji'), ('Thrissur', 'Thrissur'), ('Chandrapur', 'Chandrapur'), ('Malda', 'Malda'), ('Shimoga', 'Shimoga'), ('Junagadh', 'Junagadh'), ('Farrukhabad', 'Farrukhabad'), ('Kakinada', 'Kakinada'), ('Nizamabad', 'Nizamabad'), ('Purnia', 'Purnia'), ('Haridwar', 'Haridwar'), ('Hisar', 'Hisar'), ('Darbhanga', 'Darbhanga'), ('Tumkur', 'Tumkur'), ('Baharampur', 'Baharampur'), ('Habra', 'Habra'), ('Jalpaiguri', 'Jalpaiguri'), ('Karnal', 'Karnal'), ('Ozhukarai', 'Ozhukarai'), ('Bihar Sharif', 'Bihar Sharif'), ('Kharagpur', 'Kharagpur'), ('Aizawl', 'Aizawl'), ('Sonipat', 'Sonipat'), ('Gudiyatham', 'Gudiyatham'), ('Dewas', 'Dewas'), ('Shantipur', 'Shantipur'), ('Bathinda', 'Bathinda'), ('Jalna', 'Jalna'), ('Satna', 'Satna'), ('Mau', 'Mau'), ('Roorkee', 'Roorkee'), ('Ratlam', 'Ratlam'), ('Parbhani', 'Parbhani'), ('Sambalpur', 'Sambalpur'), ('Anantapur', 'Anantapur'), ('Imphal', 'Imphal'), ('Rajnandgaon', 'Rajnandgaon'), ('Hapur', 'Hapur'), ('Karimnagar', 'Karimnagar'), ('Arrah', 'Arrah'), ('Noida', 'Noida'), ('Etawah', 'Etawah'), ('Haldwani', 'Haldwani'), ('Bharatpur', 'Bharatpur'), ('Begusarai', 'Begusarai'), ('Sri Ganganagar', 'Sri Ganganagar'), ('Dankuni', 'Dankuni'), ('Gandhidham', 'Gandhidham'), ('Mirzapur', 'Mirzapur'), ('Sikar', 'Sikar'), ('Katihar', 'Katihar'), ('Dhulian', 'Dhulian'), ('Ranaghat', 'Ranaghat'), ('Rewa', 'Rewa'), ('Bulandshahr', 'Bulandshahr'), ('Kannur', 'Kannur'), ('Raichur', 'Raichur'), ('Pali', 'Pali'), ('Ramagundam', 'Ramagundam'), ('Silchar', 'Silchar'), ('Vizianagaram', 'Vizianagaram'), ('Nagercoil', 'Nagercoil'), ('Thanjavur', 'Thanjavur'), ('Katni', 'Katni'), ('Sambhal', 'Sambhal'), ('Singrauli', 'Singrauli'), ('Nadiad', 'Nadiad'), ('Eluru', 'Eluru'), ('Bidar', 'Bidar'), ('Munger', 'Munger'), ('Chhapra', 'Chhapra'), ('Burhanpur', 'Burhanpur'), ('Panchkula', 'Panchkula'), ('Dindigul', 'Dindigul'), ('Gandhinagar', 'Gandhinagar'), ('Hospet', 'Hospet'), ('Bhusawal', 'Bhusawal'), ('Deoghar', 'Deoghar'), ('Ongole', 'Ongole'), ('Puri', 'Puri'), ('Haldia', 'Haldia'), ('Nandyal', 'Nandyal'), ('Khandwa', 'Khandwa'), ('Morena', 'Morena'), ('Raiganj', 'Raiganj'), ('Anand', 'Anand'), ('Bhiwani', 'Bhiwani'), ('Bhind', 'Bhind'), ('Amroha', 'Amroha'), ('Hardoi', 'Hardoi'), ('Vaniyambadi', 'Vaniyambadi'), ('Morbi', 'Morbi'), ('Fatehpur', 'Fatehpur'), ('Kasaragod', 'Kasaragod'), ('Raebareli', 'Raebareli'), ('Daman', 'Daman'), ('Orai', 'Orai'), ('Chhindwara', 'Chhindwara'), ('Barmer', 'Barmer'), ('Sitapur', 'Sitapur'), ('Bahraich', 'Bahraich'), ('Phusro', 'Phusro'), ('Khammam', 'Khammam'), ('Khambhat', 'Khambhat'), ('Sirsa', 'Sirsa'), ('Modinagar', 'Modinagar'), ('Krishnanagar', 'Krishnanagar'), ('Guna', 'Guna'), ('Shivpuri', 'Shivpuri'), ('Unnao', 'Unnao'), ('Surendranagar', 'Surendranagar'), ('Balasore', 'Balasore'), ('Nabadwip', 'Nabadwip'), ('Bongaigaon', 'Bongaigaon'), ('Alappuzha', 'Alappuzha'), ('Alappuzha', 'Alappuzha'), ('Cuddalore', 'Cuddalore'), ('Hassan', 'Hassan'), ('Gadag', 'Gadag'), ('Shimla', 'Shimla'), ('Komarapalayam', 'Komarapalayam'), ('Bahadurgarh', 'Bahadurgarh'), ('Machilipatnam', 'Machilipatnam'), ('Midnapore', 'Midnapore'), ('Bharuch', 'Bharuch'), ('Hoshiarpur', 'Hoshiarpur'), ('Jaunpur', 'Jaunpur'), ('Adoni', 'Adoni'), ('Jind', 'Jind'), ('Udupi', 'Udupi'), ('Tonk', 'Tonk'), ('Tenali', 'Tenali'), ('Lakhimpur', 'Lakhimpur'), ('Balurghat', 'Balurghat'), ('Kanchipuram', 'Kanchipuram'), ('Vapi', 'Vapi'), ('Proddatur', 'Proddatur'), ('Ambur', 'Ambur'), ('Robertsonpet', 'Robertsonpet'), ('Hathras', 'Hathras'), ('Navsari', 'Navsari'), ('Banda', 'Banda'), ('Pilibhit', 'Pilibhit'), ('Mahbubnagar', 'Mahbubnagar'), ('Bettiah', 'Bettiah'), ('Vidisha', 'Vidisha'), ('Saharsa', 'Saharsa'), ('Kishangarh', 'Kishangarh'), ('Thanesar', 'Thanesar'), ('Barabanki', 'Barabanki'), ('Mughalsarai', 'Mughalsarai'), ('Veraval', 'Veraval'), ('Rudrapur', 'Rudrapur'), ('Chittorgarh', 'Chittorgarh'), ('Dibrugarh', 'Dibrugarh'), ('Chittoor', 'Chittoor'), ('Hazaribagh', 'Hazaribagh'), ('Jorhat', 'Jorhat'), ('Hindupur', 'Hindupur'), ('Porbandar', 'Porbandar'), ('Batala', 'Batala'), ('Beawar', 'Beawar'), ('Bhadravati', 'Bhadravati'), ('Hanumangarh', 'Hanumangarh'), ('Satara', 'Satara'), ('Chhatarpur', 'Chhatarpur'), ('Hajipur', 'Hajipur'), ('Damoh', 'Damoh'), ('Sasaram', 'Sasaram'), ('Nagaon', 'Nagaon'), ('Beed', 'Beed'), ('Mohali', 'Mohali'), ('Chitradurga', 'Chitradurga'), ('Tiruvannamalai', 'Tiruvannamalai'), ('Abohar', 'Abohar'), ('Harihar', 'Harihar'), ('Basirhat', 'Basirhat'), ('Kaithal', 'Kaithal'), ('Pudukkottai', 'Pudukkottai'), ('Godhra', 'Godhra'), ('Giridih', 'Giridih'), ('Pathankot', 'Pathankot'), ('Shillong', 'Shillong'), ('Bhuj', 'Bhuj'), ('Khurja', 'Khurja'), ('Bhimavaram', 'Bhimavaram'), ('Pakhanjore', 'Pakhanjore'), ('Mandsaur', 'Mandsaur'), ('Moga', 'Moga'), ('Rewari', 'Rewari'), ('Ankleshwar', 'Ankleshwar'), ('Kumbakonam', 'Kumbakonam'), ('Pandharpur', 'Pandharpur'), ('Gonda', 'Gonda'), ('Kolar', 'Kolar'), ('Yavatmal', 'Yavatmal'), ('Bankura', 'Bankura'), ('Mandya', 'Mandya'), ('Dehri', 'Dehri'), ('Kamptee', 'Kamptee'), ('Nalgonda', 'Nalgonda'), ('Madanapalle', 'Madanapalle'), ('Malerkotla', 'Malerkotla'), ('Siwan', 'Siwan'), ('Khargone', 'Khargone'), ('Mainpuri', 'Mainpuri'), ('Dholpur', 'Dholpur'), ('Lalitpur', 'Lalitpur'), ('Chakdaha', 'Chakdaha'), ('Gondia', 'Gondia'), ('Ramgarh', 'Ramgarh'), ('Darjeeling', 'Darjeeling'), ('Palwal', 'Palwal'), ('Etah', 'Etah'), ('Palakkad', 'Palakkad'), ('Rajapalayam', 'Rajapalayam'), ('Botad', 'Botad'), ('Gangapur', 'Gangapur'), ('Kottayam', 'Kottayam'), ('Deoria', 'Deoria'), ('Bhadrak', 'Bhadrak'), ('Neemuch', 'Neemuch'), ('Khanna', 'Khanna'), ('Alipurduar', 'Alipurduar'), ('Purulia', 'Purulia'), ('Guntakal', 'Guntakal'), ('Pithampur', 'Pithampur'), ('Ujhani', 'Ujhani'), ('Srikakulam', 'Srikakulam'), ('Tinsukia', 'Tinsukia'), ('Patan', 'Patan'), ('Jagdalpur', 'Jagdalpur'), ('Motihari', 'Motihari'), ('Jangipur', 'Jangipur'), ('Palanpur', 'Palanpur'), ('Dharmavaram', 'Dharmavaram'), ('Kashipur', 'Kashipur'), ('Ghazipur', 'Ghazipur'), ('Sawai Madhopur', 'Sawai Madhopur'), ('Churu', 'Churu'), ('Medininagar', 'Medininagar'), ('Dahod', 'Dahod'), ('Chirkunda', 'Chirkunda'), ('Nawada', 'Nawada'), ('Chikkamagallooru', 'Chikkamagallooru'), ('Chikmagalur', 'Chikmagalur'), ('Jetpur', 'Jetpur'), ('Gudivada', 'Gudivada'), ('Baran', 'Baran'), ('Hoshangabad', 'Hoshangabad'), ('Adilabad', 'Adilabad'), ('Muktasar', 'Muktasar'), ('Baripada', 'Baripada'), ('Hosur', 'Hosur'), ('Barnala', 'Barnala'), ('Makrana', 'Makrana'), ('Narasaraopet', 'Narasaraopet'), ('Sultanpur', 'Sultanpur'), ('Azamgarh', 'Azamgarh'), ('Bijnor', 'Bijnor'), ('Sahaswan', 'Sahaswan'), ('Basti', 'Basti'), ('Gangawati', 'Gangawati'), ('Kothamangalam', 'Kothamangalam'), ('Valsad', 'Valsad'), ('Ambikapur', 'Ambikapur'), ('Itarsi', 'Itarsi'), ('Panaji', 'Panaji'), ('Chandausi', 'Chandausi'), ('Siddipet', 'Siddipet'), ('Kalol', 'Kalol'), ('Bagaha', 'Bagaha'), ('Achalpur', 'Achalpur'), ('Gondal', 'Gondal'), ('Osmanabad', 'Osmanabad'), ('Akbarpur', 'Akbarpur'), ('Ballia', 'Ballia'), ('Deesa', 'Deesa'), ('Nagaur', 'Nagaur'), ('Bangaon', 'Bangaon'), ('Buxar', 'Buxar'), ('Firozpur', 'Firozpur'), ('Hindaun', 'Hindaun'), ('Mubarakpur', 'Mubarakpur'), ('Tanda', 'Tanda'), ('Dhubri', 'Dhubri'), ('Sehore', 'Sehore'), ('Anantnag', 'Anantnag'), ('Tadipatri', 'Tadipatri'), ('Port Blair', 'Port Blair'), ('Greater Noida', 'Greater Noida'), ('Shikohabad', 'Shikohabad'), ('Shamli', 'Shamli'), ('Kishanganj', 'Kishanganj'), ('Hinganghat', 'Hinganghat'), ('Cooch Behar', 'Cooch Behar'), ('Karaikudi', 'Karaikudi'), ('Wardha', 'Wardha'), ('Ranebennuru', 'Ranebennuru'), ('Sitamarhi', 'Sitamarhi'), ('Neyveli', 'Neyveli'), ('Amreli', 'Amreli'), ('Amreli', 'Amreli'), ('Suryapet', 'Suryapet'), ('Jamalpur', 'Jamalpur'), ('Bhiwadi', 'Bhiwadi'), ('Barshi', 'Barshi'), ('Bundi', 'Bundi'), ('Tadepalligudem', 'Tadepalligudem'), ('Miryalaguda', 'Miryalaguda'), ('Chirmiri', 'Chirmiri'), ('Betul', 'Betul'), ('Amaravati', 'Amaravati'), ('Nagapattinam', 'Nagapattinam'), ('Baraut', 'Baraut'), ('Jehanabad', 'Jehanabad'), ('Seoni', 'Seoni'), ('Rishikesh', 'Rishikesh'), ('Khair', 'Khair'), ('Dhamtari', 'Dhamtari'), ('Kapurthala', 'Kapurthala'), ('Sujangarh', 'Sujangarh'), ('Aurangabad', 'Aurangabad'), ('Chilakaluripet', 'Chilakaluripet'), ('Malappuram', 'Malappuram'), ('Kasganj', 'Kasganj'), ('Vasco', 'Vasco'), ('Tezpur', 'Tezpur'), ('Jhunjhunu', 'Jhunjhunu'), ('Datia', 'Datia'), ('Banswara', 'Banswara'), ('Raigarh', 'Raigarh'), ('Nagda', 'Nagda'), ('Lakhisarai', 'Lakhisarai'), ('Auraiya', 'Auraiya'), ('Kohima', 'Kohima'), ('Gangtok', 'Gangtok'), ('Mahuva', 'Mahuva'), ('Silvassa', 'Silvassa'), ('Balangir', 'Balangir'), ('Phagwara', 'Phagwara'), ('Jharsuguda', 'Jharsuguda'), ('Chalisgaon', 'Chalisgaon'), ('Khatauli', 'Khatauli'), ('Manjeri', 'Manjeri'), ('Mormugao', 'Mormugao'), ('Deoband', 'Deoband'), ('Mahasamund', 'Mahasamund'), ('Jagtial', 'Jagtial'), ('Viluppuram', 'Viluppuram'), ('Amalner', 'Amalner'), ('Sardarshahar', 'Sardarshahar'), ('Paramakudi', 'Paramakudi'), ('Zirakpur', 'Zirakpur'), ('Tiruchengode', 'Tiruchengode'), ('Nagina', 'Nagina'), ('Mahoba', 'Mahoba'), ('Muradnagar', 'Muradnagar'), ('Ramanagara', 'Ramanagara'), ('Kovilpatti', 'Kovilpatti'), ('Dhanpuri', 'Dhanpuri'), ('Bhadohi', 'Bhadohi'), ('Theni-Allinagaram', 'Theni-Allinagaram'), ('Khamgaon', 'Khamgaon'), ('Dhar', 'Dhar'), ('Balaghat', 'Balaghat'), ('Akot', 'Akot'), ('Fatehpur', 'Fatehpur'), ('Thalassery', 'Thalassery'), ('Bolpur', 'Bolpur'), ('Kanthi', 'Kanthi'), ('Rajpura', 'Rajpura'), ('Udgir', 'Udgir'), ('Bhandara', 'Bhandara'), ('Dadri', 'Dadri'), ('Ponnani', 'Ponnani'), ('Kadayanallur', 'Kadayanallur'), ('Pratapgarh', 'Pratapgarh'), ('Pollachi', 'Pollachi'), ('Najibabad', 'Najibabad'), ('Parli', 'Parli'), ('Ooty', 'Ooty'), ('Jhumri Telaiya', 'Jhumri Telaiya'), ('Margao', 'Margao'), ('Mancherial', 'Mancherial'), ('Karaikal', 'Karaikal'), ('Dausa', 'Dausa'), ('Jeypore', 'Jeypore'), ('Mehsana', 'Mehsana'), ('Karauli', 'Karauli'), ('Sahibganj', 'Sahibganj'), ('Kothagudem', 'Kothagudem'), ('Itanagar', 'Itanagar'), ('Bagalkot', 'Bagalkot'), ('Kavaratti', 'Kavaratti')], max_length=500, null=True)),
                ('factory_state', models.CharField(blank=True, choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Chandigarh', 'Chandigarh'), ('Dadra and Nagar Haveli', 'Dadra and Nagar Haveli'), ('Daman and Diu', 'Daman and Diu'), ('Lakshadweep', 'Lakshadweep'), ('Delhi', 'Delhi'), ('Puducherry', 'Puducherry')], max_length=500, null=True)),
                ('factory_pan', models.CharField(blank=True, max_length=500, null=True)),
                ('factory_gst', models.CharField(blank=True, max_length=500, null=True)),
                ('region', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Width',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Wwnww',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pi_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.order')),
                ('pi_no', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.pi')),
            ],
        ),
        migrations.CreateModel(
            name='OTB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otb_value', models.IntegerField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('article_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.article_type')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.buyer')),
                ('drop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.drop')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.season')),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.order')),
                ('quality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.quality')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='quality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.quality'),
        ),
        migrations.AddField(
            model_name='order',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.season'),
        ),
        migrations.AddField(
            model_name='order',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.supplier'),
        ),
        migrations.CreateModel(
            name='New_Order_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.IntegerField(blank=True, null=True)),
                ('price', models.IntegerField(blank=True, null=True)),
                ('value', models.IntegerField(blank=True, null=True)),
                ('del_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.new_order')),
                ('quality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.quality')),
            ],
        ),
        migrations.AddField(
            model_name='new_order',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.season'),
        ),
        migrations.AddField(
            model_name='new_order',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.supplier'),
        ),
        migrations.CreateModel(
            name='Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('comments', models.CharField(blank=True, max_length=2000, null=True)),
                ('detail', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.discussion')),
            ],
        ),
        migrations.CreateModel(
            name='Calender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('activity_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.activity')),
                ('buyer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.buyer')),
                ('drop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.drop')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.season')),
            ],
        ),
        migrations.CreateModel(
            name='Assortment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('options', models.IntegerField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('inward_month', models.CharField(blank=True, max_length=100, null=True)),
                ('content1', models.CharField(blank=True, max_length=100, null=True)),
                ('content2', models.CharField(blank=True, max_length=100, null=True)),
                ('content3', models.CharField(blank=True, max_length=100, null=True)),
                ('assortment_date', models.DateField(blank=True, null=True)),
                ('techpack', models.CharField(blank=True, max_length=100, null=True)),
                ('article_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.article_type')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.buyer')),
                ('domimp', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.domimp')),
                ('drop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.drop')),
                ('fabric_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.fabric_type')),
                ('gender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.gender')),
                ('onoff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.onoff')),
                ('order_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.order_type')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.season')),
                ('wwnww', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.wwnww')),
            ],
        ),
        migrations.AddField(
            model_name='activity',
            name='department_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='main.department'),
        ),
    ]
