# Generated by Django 3.2.20 on 2024-07-19 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
