# Generated by Django 3.2.20 on 2024-07-19 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_discussion_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='dis_status',
            field=models.IntegerField(blank=True, choices=[('1', 'Open'), ('2', 'Close')], null=True),
        ),
    ]
