# Generated by Django 3.2.20 on 2024-07-19 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_discussion_dis_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='dis_status',
            field=models.CharField(blank=True, choices=[('Open', 'Open'), ('Close', 'Close')], max_length=100, null=True),
        ),
    ]
