# Generated by Django 3.2.20 on 2024-07-19 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_discussion_dis_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='details',
            name='next_follow_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
